### ISSUE TITLE
Check arguments *before* doing allocations

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#35]
e.g. currently:
```lua
> p = require "pgsql"
> c = p.connectdb()
stdin:1: bad argument #1 to 'connectdb' (string expected, got pgsql connection methods)
stack traceback:
	[C]: in function 'pgsql.connectdb'
	stdin:1: in main chunk
	[C]: in ?
```

This is because in `pgsql_connectdb` you call `pgsql_conn_new` *before* calling `luaL_checkstring`.

Order should be:
1. Check all arguments (using e.g. `luaL_checkstring`)
2. Allocate all space needed for results
3. Make the actual call

**Comment by mbalmer** [comment]
Fixed in 40dc68c

**Comment by mbalmer** [comment]
grr, now it potentially can leak..

**Comment by mbalmer** [comment]
Ok, fixed in 103fbe1b8656dffa1e14a54ad83e559e3e98a1e5

**Comment by daurnimator** [comment]
Thanks. That looks better.

**Comment by daurnimator** [comment]
Though this is still a problem in e.g. `pgsql_encryptPassword`. The `gcmalloc` pushes a userdata onto the stack. You need to move the `luaL_checkstring`s to the top of the functions.

**Comment by mbalmer** [comment]
> Am 11.05.2016 um 10:28 schrieb daurnimator <notifications@github.com>:
> 
> Though this is still a problem in e.g. pgsql_encryptPassword. The gcmalloc pushes a userdata onto the stack. You need to move the luaL_checkstrings to the top of the functions.
> 
> 
It would do no harm, since I use absolute indexes, but you are right, it's nicer to check first. I'll change that.

**Comment by daurnimator** [comment]
> It would do no harm, since I use absolute indexes, but you are right, it's nicer to check first. I'll change that.

It does create incorrect error messages.
e.g. if I call `pgsql_encryptPassword` with no arguments it will tell me `string expected, got pgsql garbage collected memory`

**Comment by daurnimator** [comment]
I see you fixed `pgsql_encryptPassword` in c5254c0d3bb279c327ba6e08e34a5da8e01028dc. 
It also needs doing to `conn_unescapeBytea`
